<a href="https://colab.research.google.com/github/sahithya-uic/ColabStuff/blob/main/first_googlecolab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import torch

In [4]:
!uname -a

Linux 7e74331b8e8e 5.10.147+ #1 SMP Sat Dec 10 16:00:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


In [5]:
tf.__version__

'2.11.0'

In [2]:
from torch import nn #import torch.nn as nn


In [3]:
x = 5
y = 6


In [4]:
from os import XATTR_SIZE_MAX
class Net(nn.Module):
  def __init__(self, input_sz=1):
    super(Net, self).__init__()
    self.layer = nn.Linear(input_sz, 1)
    self.input_sz = input_sz
  
  def forward(self,x):
    x = self.layer(x)
    return x


In [6]:
model = Net(input_sz=10)

In [8]:
model2 = Net()

In [9]:
model.input_sz

10

In [12]:
input = torch.tensor(2.).unsqueeze(0)
input

tensor([2.])

In [13]:
model2.forward(input)

tensor([1.8558], grad_fn=<AddBackward0>)

In [14]:
model2(input)

tensor([1.8558], grad_fn=<AddBackward0>)

In [15]:
for i in range(5):
  print(i)

0
1
2
3
4


In [16]:
if (i<2):
  print('yes')
else:
  print('no')

no


In [17]:
i

4

How to load a file

In [23]:
import urllib.request
url = "https://media.nbcchicago.com/2019/09/277c89814ef248b6bdec6789c4727faf.jpg?quality=85&strip=all&resize=1200%2C675"
urllib.request.urlretrieve(url,'sunrise.jpg')


('sunrise.jpg', <http.client.HTTPMessage at 0x7f241f006730>)